version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    networks:
      - microservices-network

  producer:
    build:
      context: ./producer
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  consumer:
    build:
      context: ./consumer
    ports:
      - "8081:8081"
    networks:
      - microservices-network

networks:
  microservices-network:
