version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - microservices-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - microservices-network

  producer:
    build:
      context: ./producer
    container_name: producer
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - kafka

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - kafka

networks:
  microservices-network:
